### ISSUE TITLE
violation of styling guidelines

### ISSUE THREAD

**Issue by zhaoxuyll** [golf1052/base16-vscode#3]
Should status bar color is `base01`?

I see base16/styling.md:
![image](https://user-images.githubusercontent.com/3224165/88798305-4724f680-d1d7-11ea-8448-603307b8ae8b.png)

But base16-vscode/templates/default.mustache:
![image](https://user-images.githubusercontent.com/3224165/88798394-67ed4c00-d1d7-11ea-8c52-db106d46b921.png)

**Comment by golf1052** [comment]
The status bar background in the default VSCode theme is blue
![image](https://user-images.githubusercontent.com/1903871/95646593-f0f9ec80-0a7e-11eb-8ce1-9faa2a647ba8.png)

and the default status bar color changes based upon the editor context, for example the status bar background color in the default VSCode theme when debugging is orange

![image](https://user-images.githubusercontent.com/1903871/95646618-4fbf6600-0a7f-11eb-9ebe-6d7617b57e6e.png)

Because I want status bars to be distinct between these context and because I want the extension to be somewhat similar to the default theme colors, I set the `statusBar.background` color to base0D which is the blue color for themes.
